apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: db-service
    spec:
      selector:
        app: db
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: db-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: db
      template:
        metadata:
          labels:
            app: db
        spec:
          containers:
            - name: db-container
              image: postgres
              env:
                - name: POSTGRES_USER
                  value: example
                - name: POSTGRES_PASSWORD
                  value: example

  - apiVersion: v1
    kind: Service
    metadata:
      name: adminer-service
    spec:
      selector:
        app: adminer
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      type: LoadBalancer
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: adminer-deployment
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: adminer
      template:
        metadata:
          labels:
            app: adminer
        spec:
          containers:
            - name: adminer-container
              image: adminer
